[package]
name = "analytics"
version = "0.1.0"
edition = "2024"

[dependencies]
kamadak-exif = "0.6.1"
serde = { version = "1.0", features = ["derive"] }
csv = "1.3"
sha2 = "0.10.9"
chrono = "0.4.42"
media_info = "0.6.0"
rusqlite = "0.38.0"
